<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>transdb_backend_net</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>ebdb8ffe-c2ad-452e-ae59-6daa76fc03d1</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="libphonenumber-csharp" Version="9.0.31" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
        <PackageReference Include="String.Similarity" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
